export default {
	state: {
		carId: '',
		idResult: [
			{
				CusNo: '',
				Date_Receive: '',
				CusNo_Old: '',
				Picture: '',
				Be: '',
				BeType: '',
				company_type: '',
				Cus_Name: '',
				Cus_Surename: '',
				Cus_Nickname: '',
				cus_branch_id: '',
				cus_branch_txt: '',
				Cus_Big_Picture: '',
				Cus_Small_Picture: '',
				Sex: '',
				DateOfBirth: '',
				Cus_IDNo: '',
				Primary_Edu: '',
				Secondary_Edu: '',
				Highschool_Edu: '',
				Bachelor: '',
				Master: '',
				Phd: '',
				Status: '',
				mary_id: '',
				C_copy: '',
				C_Add: '',
				C_Vill: '',
				C_Tum: '',
				C_Amp: '',
				C_Pro: '',
				C_GEO: '',
				C_Code: '',
				C_AddGPSLatitude: '',
				C_AddGPSLongtitude: '',
				C_AddMapDescribe: '',
				Cus_Coppy: '',
				Cus_Add: '',
				Cus_Vil: '',
				Cus_Tum: '',
				Cus_Amp: '',
				Cus_Pro: '',
				Cus_GEO: '',
				Cus_Code: '',
				Cus_AddGPSLatitude: '',
				Cus_AddGPSLongtitude: '',
				Cus_AddMapDescribe: '',
				NotMail: '',
				H_Tel: '',
				JobID: '',
				Job: '',
				JobSegmentGroup: '',
				Job_Des: '',
				W_Name: '',
				Title: '',
				W_Coppy: '',
				W_Add: '',
				W_Vill: '',
				W_Tum: '',
				W_Amp: '',
				W_Pro: '',
				W_GEO: '',
				W_Code: '',
				W_Tel: '',
				W_Fax: '',
				W_Email: '',
				Cus_WGPSLatitude: '',
				Cus_WGPSLongtitude: '',
				Cus_WMapDescribe: '',
				Pagger: '',
				M_Tel: '',
				Email: '',
				Cus_Type: '',
				Data_Received: '',
				Data_Received_Num: '',
				Remark: '',
				Updater: '',
				UpdaterNO: '',
				UpdateT: '',
				Resperson: '',
				Resperson_posCode: '',
				respon_date: '',
				Time_for_talk: '',
				Pleasure_value: '',
				rcheck: '',
				cleansing_status: '',
				cleansing_date: '',
				status_up: '',
			},
		],
		customerResults: [
			{
				CusNo: '',
				Date_Receive: '',
				CusNo_Old: '',
				Picture: '',
				Be: '',
				BeType: '',
				company_type: '',
				Cus_Name: '',
				Cus_Surename: '',
				Cus_Nickname: '',
				cus_branch_id: '',
				cus_branch_txt: '',
				Cus_Big_Picture: '',
				Cus_Small_Picture: '',
				Sex: '',
				DateOfBirth: '',
				Cus_IDNo: '',
				Primary_Edu: '',
				Secondary_Edu: '',
				Highschool_Edu: '',
				Bachelor: '',
				Master: '',
				Phd: '',
				Status: '',
				mary_id: '',
				C_copy: '',
				C_Add: '',
				C_Vill: '',
				C_Tum: '',
				C_Amp: '',
				C_Pro: '',
				C_GEO: '',
				C_Code: '',
				C_AddGPSLatitude: '',
				C_AddGPSLongtitude: '',
				C_AddMapDescribe: '',
				Cus_Coppy: '',
				Cus_Add: '',
				Cus_Vil: '',
				Cus_Tum: '',
				Cus_Amp: '',
				Cus_Pro: '',
				Cus_GEO: '',
				Cus_Code: '',
				Cus_AddGPSLatitude: '',
				Cus_AddGPSLongtitude: '',
				Cus_AddMapDescribe: '',
				NotMail: '',
				H_Tel: '',
				JobID: '',
				Job: '',
				JobSegmentGroup: '',
				Job_Des: '',
				W_Name: '',
				Title: '',
				W_Coppy: '',
				W_Add: '',
				W_Vill: '',
				W_Tum: '',
				W_Amp: '',
				W_Pro: '',
				W_GEO: '',
				W_Code: '',
				W_Tel: '',
				W_Fax: '',
				W_Email: '',
				Cus_WGPSLatitude: '',
				Cus_WGPSLongtitude: '',
				Cus_WMapDescribe: '',
				Pagger: '',
				M_Tel: '',
				Email: '',
				Cus_Type: '',
				Data_Received: '',
				Data_Received_Num: '',
				Remark: '',
				Updater: '',
				UpdaterNO: '',
				UpdateT: '',
				Resperson: '',
				Resperson_posCode: '',
				respon_date: '',
				Time_for_talk: '',
				Pleasure_value: '',
				rcheck: '',
				cleansing_status: '',
				cleansing_date: '',
				status_up: '',
			},
		],
	},
	mutations: {
		getCustomerSuccess(state, customerResults) {
			state.loading = false;
			state.customerResults = customerResults;
		},
		setid(state, id) {
			state.idResult = id;
		},

		setCarIdState(state, id) {
			state.carId = id;
		},
	},

	actions: {
		async setCustomerInfo({ commit, state }, customer) {
			let customerInfo = '';
			try {
				if (customer) {
					customerInfo = await this.$axios.get(`${process.env.VhcUrl}/Car/getcarowner?CusNo=` + customer);
				} else {
					customerInfo = await this.$axios.get(`${process.env.VhcUrl}/Car/getcarowner?CusNo=` + state.idResult);
				}
				commit('getCustomerSuccess', customerInfo.data || '');

				// console.log(state.customerResults);
			} catch (error) {}
		},
		// eslint-disable-next-line require-await
		async setcusId({ commit }, id) {
			try {
				// console.log('setcusId store : ', id);
				await commit('setid', id);
			} catch (error) {
				commit('carError', error.message);
			}
		},
		setCarId({ commit, state }, id) {
			try {
				state.carId = '';
				commit('setCarIdState', id);
			} catch (error) {
				commit('carError', error.message);
			}
		},
	},
};
